snowflake-db:
  outputs:
    dev:
      account: yyrutpn-zc57919
      database: DBT_TEST
      password: pTfQ54NSVURfWsj
      role: accountadmin
      schema: TPCH_SF1
      threads: 1
      type: snowflake
      user: girishahb
      warehouse: compute_wh
  target: dev
